import { Component, OnInit, inject, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ReportService } from '../../../core/services/api.services';
import { LanguageService } from '../../../core/services/language.service';
import { SkeletonComponent } from '../../../shared/components/skeleton/skeleton.component';
import { MonthlyReport } from '../../../core/models';

/**
 * Student's own monthly reports — auto-generated by the MonthlyReportJob on the 1st.
 * Backend: GET /api/reports/my (Student-only).
 */
@Component({
  selector: 'app-student-reports',
  standalone: true,
  imports: [CommonModule, SkeletonComponent],
  template: `
    <div class="page-fade">
      <div class="section-header">
        <div>
          <h1 class="section-title">{{ isAr() ? 'تقاريري' : 'My Reports' }}</h1>
          <p class="section-subtitle">{{ isAr() ? 'تقاريري الشهرية' : 'My monthly reports' }}</p>
        </div>
      </div>

      @if (loading()) { <app-skeleton type="card"/> }
      @else if (!reports().length) {
        <div class="card"><div class="card-body text-center py-5 text-secondary">
          <i class="bi bi-graph-up d-block mb-2 fs-1 opacity-40"></i>
          <p class="mb-0">{{ isAr()
            ? 'لا توجد تقارير بعد. التقارير تظهر في بداية كل شهر بعد تجميع بيانات الحضور والواجبات.'
            : 'No reports yet. Reports appear at the start of each month once attendance and assignment data are aggregated.' }}</p>
        </div></div>
      } @else {
        <div class="row g-3">
          @for (r of reports(); track r.id) {
            <div class="col-md-6 col-lg-4">
              <div class="card h-100">
                <div class="card-body">
                  <div class="d-flex align-items-center justify-content-between mb-3">
                    <strong style="font-size:.95rem">{{ monthName(r.month) }} {{ r.year }}</strong>
                    <span class="badge" [class]="gradeBadge(r.grade)" style="font-size:.8rem;padding:.4rem .65rem">{{ r.grade }}</span>
                  </div>

                  <!-- Score breakdown -->
                  <div class="mb-2">
                    <div class="d-flex justify-content-between" style="font-size:.78rem"><span>{{ isAr()?'الحضور':'Attendance' }}</span><span class="fw-medium">{{ r.attendanceScore | number:'1.0-1' }}%</span></div>
                    <div class="progress mt-1" style="height:4px"><div class="progress-bar bg-primary" [style.width.%]="r.attendanceScore"></div></div>
                  </div>
                  <div class="mb-2">
                    <div class="d-flex justify-content-between" style="font-size:.78rem"><span>{{ isAr()?'الواجبات':'Assignments' }}</span><span class="fw-medium">{{ r.assignmentScore | number:'1.0-1' }}%</span></div>
                    <div class="progress mt-1" style="height:4px"><div class="progress-bar bg-success" [style.width.%]="r.assignmentScore"></div></div>
                  </div>
                  <div class="mb-3">
                    <div class="d-flex justify-content-between" style="font-size:.78rem"><span>{{ isAr()?'الاختبارات':'Exams' }}</span><span class="fw-medium">{{ r.quizScore | number:'1.0-1' }}%</span></div>
                    <div class="progress mt-1" style="height:4px"><div class="progress-bar bg-warning" [style.width.%]="r.quizScore"></div></div>
                  </div>

                  <hr>
                  <div class="text-center">
                    <small class="text-secondary d-block">{{ isAr()?'الإجمالي':'Overall' }}</small>
                    <strong style="font-size:1.4rem">{{ r.overallScore | number:'1.0-1' }}%</strong>
                  </div>

                  @if (r.recommendationAr || r.recommendationEn) {
                    <hr>
                    <small class="text-secondary d-block" style="font-size:.78rem;line-height:1.5">
                      <i class="bi bi-lightbulb me-1 text-warning"></i>
                      {{ isAr() ? r.recommendationAr : r.recommendationEn }}
                    </small>
                  }
                </div>
              </div>
            </div>
          }
        </div>
      }
    </div>
  `
})
export class StudentReportsComponent implements OnInit {
  private readonly reportSvc = inject(ReportService);
  readonly lang = inject(LanguageService);
  readonly isAr = this.lang.isRtl;

  readonly reports = signal<MonthlyReport[]>([]);
  readonly loading = signal(true);

  ngOnInit() {
    this.reportSvc.getMyReports().subscribe(r => {
      if (r.success && r.data) this.reports.set(r.data);
      this.loading.set(false);
    });
  }

  monthName(m: number): string {
    const monthsAr = ['يناير','فبراير','مارس','أبريل','مايو','يونيو','يوليو','أغسطس','سبتمبر','أكتوبر','نوفمبر','ديسمبر'];
    const monthsEn = ['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'];
    const arr = this.isAr() ? monthsAr : monthsEn;
    return arr[m - 1] || String(m);
  }

  gradeBadge(g: string): string {
    if (!g) return 'bg-secondary';
    const c = g.toUpperCase().charAt(0);
    return c === 'A' ? 'bg-success' : c === 'B' ? 'bg-info' : c === 'C' ? 'bg-warning text-dark' : 'bg-danger';
  }
}
